Annual faculty promotions.WebUI/Areas/UserArea/Controllers/UnivercityStructureController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Annual_faculty_promotions.Core.Domain;
using Annual_faculty_promotions.Data;
using Annual_faculty_promotions.Service.Contracts;
using Annual_faculty_promotions.WebUI.Helpers.Filters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Annual_faculty_promotions.Core.Enums;
using Microsoft.AspNet.Identity;

namespace Annual_faculty_promotions.WebUI.Areas.UserArea.Controllers
{
    public partial class UnivercityStructureController : Controller
    {
        private readonly IUnivercityStructureService _univercityStructureService;
        private readonly ILogService _logService;
        private readonly IUnitOfWork _unitOfWork;

        public UnivercityStructureController(IUnitOfWork unitOfWork, ILogService logService, IUnivercityStructureService univercityStructureService)
        {
            _unitOfWork = unitOfWork;
            _logService = logService;
            _univercityStructureService = univercityStructureService;

        }

        //[Expire]
        public virtual ActionResult Index()
        {
            return View();
        }

        public virtual ActionResult GetStructuresTreeNode()
        {
            try
            {
                List<JObject> jobjects = new List<JObject>();

                var items = _univercityStructureService.GetAllUnivercityStructures();

                if (items.Any())
                {
                    var rootNodes = items.Where(c => c.Level == 1);
                    foreach (var node in rootNodes)
                    {
                        JObject root = new JObject
                      {
                        {"id",node.Id},
                        {"text",node.Name},
                        {"hasChild",node.HasChild},
                        {"level",node.Level}
                      };
                        root.Add("children", this.GetChild(node, items));
                        jobjects.Add(root);
                    }
                }
                return Content(JsonConvert.SerializeObject(jobjects));
            }
            catch (Exception)
            {
                return Json(new { isError = true, Msg = "خطا در لود ساختار دانشگاه" });
            }
        }
        private JArray GetChild(UnivercityStructure parentNodes, IEnumerable<UnivercityStructure> nodes)
        {
            JArray childArray = new JArray();

            foreach (var node in nodes.Where(x => x.ParentId == parentNodes.Id))
            {
                JObject subObject = new JObject
                {
                    {"id",node.Id},
                    {"text",node.Name},
                    {"hasChild",node.HasChild},
                    {"level",node.Level}
                };

                if (nodes.Any(y => y.ParentId == node.Id))
                {
                    subObject.Add("children", this.GetChild(node, nodes));
                }
                childArray.Add(subObject);
            }
            return childArray;
        }

        [HttpPost]
        [AjaxOnly]
        [OutputCache(NoStore = true, Duration = 0)]
        public virtual ActionResult Create(UnivercityStructure univercityStructure)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Msg = "خطا - ثبت نشد" });
                }
                _univercityStructureService.AddNewUnivercityStructure(univercityStructure);
                Log log = new Log()
                {
                    UserId = int.Parse(User.Identity.GetUserId()),
                    Operation = Operations.ساختار_دانشگاه,
                    OperationDetail = OperationsDetail.ایجاد,
                    Description = " ایجاد ساختار دانشگاه-" + univercityStructure.Name
                };
                _logService.AddNewLog(log);
                _unitOfWork.SaveChanges();
                return Json(new { Msg = "ثبت شد" });
            }
            catch (Exception)
            {
                return Json(new { isError = true, Msg = "خطا در ایجاد ساختار دانشگاه" });
            }
        }

        public virtual ActionResult GetCategoriesTreeNode()
        {
            try
            {
                List<JObject> jobjects = new List<JObject>();

                var items = _univercityStructureService.GetAllUnivercityStructures();

                if (items.Any())
                {
                    var rootNodes = items.Where(c => c.Level == 1);
                    foreach (var node in rootNodes)
                    {
                        JObject root = new JObject
                      {
                        {"id",node.Id},
                        {"text",node.Name},
                        {"level",node.Level}
                      };
                        root.Add("children", this.GetChild(node, items));
                        jobjects.Add(root);
                    }
                }
                return Content(JsonConvert.SerializeObject(jobjects));
            }
            catch (Exception)
            {
                return Json(new { isError = true, Msg = "خطا در لود ساختار دانشگاه" });
            }
        }

        private JArray GetChild(UnivercityStructure parentNodes, IList<UnivercityStructure> nodes)
        {
            JArray childArray = new JArray();

            foreach (var node in nodes.Where(x => x.ParentId == parentNodes.Id))
            {
                JObject subObject = new JObject
                {
                    {"id",node.Id},
                    {"text",node.Name},
                    {"level",node.Level}
                };

                if (nodes.Any(y => y.ParentId == node.Id))
                {
                    subObject.Add("children", this.GetChild(node, nodes));
                }
                childArray.Add(subObject);
            }
            return childArray;
        }

        [HttpPost]
        [AjaxOnly]
        public virtual ActionResult Delete(int id)
        {
            try
            {
                var model = _univercityStructureService.Where(d => d.ParentId == id || (d.Id == id && d.ParentId == null)).FirstOrDefault();
                if (model != null)
                    return Json(new { isError = true, Msg = "این گروه آموزشی دارای زیر شاخه می باشد!" });
                model = _univercityStructureService.Where(s=>s.Id==id).Include(i=>i.Requests).FirstOrDefault();
                if (model == null)
                    return Json(new { isError = true, Msg = "رکورد مورد نظر یافت نشد!" });
                if (model.Requests.Count > 0)
                {
                    return Json(new { isError = true, Msg = "این گروه آموزشی دارای گردش می باشد!" });
                }
                _univercityStructureService.Delete(id);
                Log log = new Log()
                {
                    UserId = int.Parse(User.Identity.GetUserId()),
                    Operation = Operations.ساختار_دانشگاه,
                    OperationDetail = OperationsDetail.حذف,
                    Description = " حذف ساختار دانشگاه به شماره" + id
                };
                _logService.AddNewLog(log);
                _unitOfWork.SaveChanges();
                return Json(new { isError = false, Msg = "حذف شد" });
            }
            catch (Exception)
            {
                return Json(new { isError = true, Msg = "حذف نشد" });
            }
        }

        public virtual ActionResult Edit(int? univercityId)
        {
            if (univercityId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var college = _univercityStructureService.Find(univercityId);
            if (college == null)
            {
                return HttpNotFound();
            }
            return PartialView("_edit", college);
        }

        [HttpPost]
        public virtual ActionResult Edit(UnivercityStructure univercity)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { success = false, Msg = "ورودی نامعتبر" });
                }
                _univercityStructureService.EditUnivercityStructure(univercity);
                Log log = new Log()
                {
                    UserId = int.Parse(User.Identity.GetUserId()),
                    Operation = Operations.ساختار_دانشگاه,
                    OperationDetail = OperationsDetail.ویرایش,
                    Description = " ویرایش ساختار دانشگاه به شماره" + univercity.Id
                };
                _logService.AddNewLog(log);
                _unitOfWork.SaveChanges();
                return Json(new { success = true, Msg = "تغییرات اعمال شد" });
            }
            catch (Exception)
            {
                return Json(new { isError = true, Msg = "خطا در ویرایش ساختار دانشگاه" });
            }
        }
    }
}

Annual faculty promotions.WebUI/Areas/UserArea/Views/UnivercityStructure/Index.cshtml
@{Layout = "~/Areas/UserArea/Views/Shared/_Layout.cshtml";}
<ul class="breadcrumb breadcrumb-page">
    <li><a href="javascript:void(0)">صفحه اصلی</a></li>
    <li class="active"><a href="javascript:void(0)">تعریف ساختار دانشگاه</a></li>
</ul>


<div class="easyui-panel" style="padding:5px;margin-bottom: 5px">
    <a href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-add'" onclick="$('#dlgAddStructure').dialog('open').dialog('setTitle', 'جدید');">جدید</a>
    <a id="btnStructureEdit" onclick="showdlgUnivercityEdit()" href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-edit',disabled:true">ویرایش</a>
    <a id="btnStructureDelete" href="javascript:void(0)" onclick="destroyStructure();" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-remove',disabled:true">حذف</a>
</div>

<div class="easyui-panel" style="padding: 5px; height: 450px;">
    <ul style="margin-top: 5px" id="uniTree"></ul>
</div>


<div id="dlgAddStructure" class="easyui-dialog" modal="true" style="width: 500px; height: 170px; padding: 10px 20px"
     closed="true" buttons="#dlgAddStructure-buttons">
    @Html.Partial("_Create")
    <div id="dlgAddStructure-buttons">
        <a href="javascript:void(0)" class="easyui-linkbutton c6" iconcls="icon-ok" onclick="saveStructure();" style="width: 90px">ذخیره</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-cancel" onclick=" javascript: $('#dlgAddStructure').dialog('close'); " style="width: 90px">انصراف</a>
    </div>
</div>

<div id="dlgEditStructure" class="easyui-dialog" modal="true" style="width: 500px; height: 170px; padding: 10px 20px"
     closed="true" buttons="#dlgEditStructure-buttons">
</div>
<div id="dlgEditStructure-buttons">
    <a href="javascript:void(0)" class="easyui-linkbutton c6 " iconcls="icon-ok" onclick="updateStructure();" style="width: 90px">ذخیره</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-cancel" onclick=" javascript: $('#dlgEditStructure').dialog('close'); " style="width: 90px">انصراف</a>
</div>

@section scripts{

    @Scripts.Render("~/bundles/jqueryAjaxForm")
    <script>
        $(function() {
            $('[data-toggle]').tooltip({
                placement: 'bottom'
            });
        });

        $('#frmAddStructure').ajaxForm();

        var selectedNodeId;

        $('#uniTree').tree({
            title: 'test',
            url: '@Url.Action("GetStructuresTreeNode", "UnivercityStructure", new {area = "UserArea"})',
            required: true,
            lines: true,
            fit: true,
            onLoadSuccess: function() {
                var node = $('#uniTree').tree('find', selectedNodeId);
                if (node) {
                    $('#uniTree').tree('select', node.target);
                }
            },
            onSelect: function(node) {
                selectedNodeId = node.id;
                $('#ParentId').val(selectedNodeId);
                $('#btnStructureEdit').linkbutton('enable');
                $('#btnStructureDelete').linkbutton('enable');

            }
        });

        function saveStructure() {
            var node = $('#uniTree').tree('getSelected');
            if (node != null) {
                if (node.hasChild == false) {
                    $.messager.alert('warning', 'امکان درج مقدار برای این ساختار وجود ندارد');
                    myalert('امکان درج مقدار برای این ساختار وجود ندارد', 'danger');
                    return;
                }
                $('#Level').val(node.level + 1);
            } else {
                $('#Level').val(1);
            }

            if ($('#frmAddStructure').valid()) {
                $('#frmAddStructure').ajaxSubmit({
                    cashe: false,
                    url: '@Url.Action("Create", "UnivercityStructure", new {area = "UserArea"}, "http")',
                    type: 'Post',
                    dataType: 'json',
                    data: $('#frmAddStructure').serialize(),
                    success: function(result) {
                        if (result.isError) {
                            myalert(result.Msg, 'danger');
                        } else {
                            $('#Name').val('');
                            $('#uniTree').tree('reload');
                            myalert(result.Msg, 'success');
                        }
                    },
                    error: function(xhr, status) {
                        xhr.responseText();
                    }
                });
            } else {
                return $(this).form('validate');
            }
        }


        function destroyStructure() {
            $.messager.confirm('confirm', 'حذف شود؟', function(r) {
                if (r) {
                    var node = $('#uniTree').tree('getSelected');
                    if (node == null) return;
                    $.post('@Url.Action("Delete", "UnivercityStructure", new {area = "UserArea"}, "http")',
                    { id: node.id }, function(result) {
                        if (result.isError) {
                            myalert(result.Msg, 'danger');
                        } else {
                            myalert(result.Msg, 'success');
                            $('#uniTree').tree('reload');
                        }
                    }, 'json');
                }
            });
        }

        function showdlgUnivercityEdit() {
            var node = $('#uniTree').tree('getSelected');
            if (node == null) return;
            $.ajax({
                url: '@Url.Action("Edit", "UnivercityStructure", new {area = "UserArea"})',
                dataType: 'html',
                type: 'get',
                data: { univercityId: node.id },
                success: function(result) {
                    $('#dlgEditStructure').html(result);
                    $('#dlgEditStructure').dialog('open').dialog('setTitle', 'ویرایش');
                },
                error: function() {

                }
            });
        }

        function updateStructure() {
            if ($('#frmEditStructure').valid()) {
                $('#frmEditStructure').ajaxSubmit({
                    cashe: false,
                    url: '@Url.Action("Edit", "UnivercityStructure", new {area = "UserArea"}, "http")',
                    type: 'Post',
                    dataType: 'json',
                    data: $('#frmEditStructure').serialize(),
                    success: function(result) {
                        if (result.isError) {
                            myalert(result.Msg, 'danger');
                        } else {
                            $('#frmEditStructure').form('clear');
                            $('#uniTree').tree('reload');
                            myalert(result.Msg, 'success');
                        }
                    },
                    error: function(xhr, status) {
                        xhr.responseText();
                    }
                });
            } else {
                return $(this).form('validate');
            }
        }
    </script>
}

Annual faculty promotions.WebUI/Areas/UserArea/Views/UnivercityStructure/_Create.cshtml
@model Annual_faculty_promotions.Core.Domain.UnivercityStructure
@using (Html.BeginForm("Create", "UnivercityStructure", FormMethod.Post, new { id = "frmAddStructure", @class = "form-horizontal" }))
{
  
    
      @Html.TextBoxFor(model => model.ParentId,new{hidden="hidden"})
       @Html.TextBoxFor(model => model.Level,new{hidden="hidden"})
    <div class="form-group form-group-sm">
        @Html.LabelFor(model => model.Name, new {@class = "col-sm-2 control-label"})
        <div class="col-sm-7">
            @Html.TextBoxFor(model => model.Name, new {@class = "form-control input-sm"})
        </div>
    </div>
    <div class="form-group form-group-sm">
        @Html.LabelFor(model => model.HasChild, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-8">
            @Html.EditorFor(model => model.HasChild, new { @class = "form-control input-sm" })
        </div>
    </div>
}

Annual faculty promotions.WebUI/Areas/UserArea/Views/UnivercityStructure/_Edit.cshtml
@model Annual_faculty_promotions.Core.Domain.UnivercityStructure
@using (Html.BeginForm("Create", "UnivercityStructure", FormMethod.Post, new { id = "frmEditStructure", @class = "form-horizontal" }))
{

    @Html.TextBoxFor(model => model.Id, new { hidden = "hidden" })
    @Html.TextBoxFor(model => model.ParentId, new { hidden = "hidden" })
    @Html.TextBoxFor(model => model.Level, new { hidden = "hidden" })
    <div class="form-group form-group-sm">
        @Html.LabelFor(model => model.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-7">
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control input-sm" })
        </div>
    </div>
    <div class="form-group form-group-sm">
        @Html.LabelFor(model => model.HasChild, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-8">
            @Html.EditorFor(model => model.HasChild, new { @class = "form-control input-sm" })
        </div>
    </div>
}